server {
  listen 8080;
  server_name _;

   location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    default_type "text/plain";
  }

  location / {
    return 301 https://$host$request_uri;
  }
} 

server {
  listen 8443 ssl;
  server_name l1-6.tonyephec.cloud www.l1-6.tonyephec.cloud;

  ssl_certificate     /etc/letsencrypt/live/l1-6.tonyephec.cloud/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/l1-6.tonyephec.cloud/privkey.pem;

  ssl_protocols       TLSv1.2 TLSv1.3;
  ssl_ciphers         HIGH:!aNULL:!MD5;
  ssl_session_cache   shared:SSL:10m;
  ssl_session_timeout 1h;

  # En-têtes de sécurité
  add_header Strict-Transport-Security "max-age=31536000" always;
  add_header X-Content-Type-Options    "nosniff" always;
  add_header X-Frame-Options           "SAMEORIGIN" always;
  add_header Referrer-Policy           "strict-origin-when-cross-origin" always;

  client_max_body_size 1m;

  location /api {
    # limit_req zone=api_limit burst=20 nodelay;
    proxy_pass http://api:5000;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    proxy_pass http://front:80;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # LIMITATION PÉDAGOGIQUE — ne pas retirer (simulation de fort trafic, TP8)
    limit_rate 300k;
  }
}
