options {
  directory "/var/cache/bind";
  version "not currently available";
  allow-query { any; };
  allow-query-cache { none; };
  recursion no;
};

zone "l1-6.tonyephec.cloud." {
  type master;
  inline-signing yes;
  dnssec-policy default;
  file "/etc/bind/l1-6.zone";
  allow-transfer {
    none;
  };
};
